#!/bin/bash

echo "================================"
echo "Configuração Firebase - Art Madeiras"
echo "================================"
echo ""
echo "Projeto Firebase Configurado:"
echo "  Nome: Art-Madeiras"
echo "  ID: art-madeiras"
echo "  Número: 757919568230"
echo ""
echo "Arquivos Atualizados:"
echo "  ✅ google-services.json"
echo "  ✅ ArteApplication.kt (inicialização Firebase)"
echo "  ✅ AndroidManifest.xml"
echo ""
echo "================================"
echo "Próximas Etapas no Firebase Console:"
echo "================================"
echo ""
echo "1️⃣  AUTHENTICATION"
echo "   - Firebase Console → Authentication"
echo "   - Enable Email/Password"
echo ""
echo "2️⃣  FIRESTORE DATABASE"
echo "   - Firebase Console → Firestore Database"
echo "   - Create Database (Production Mode)"
echo "   - Region: southamerica-east1"
echo ""
echo "3️⃣  SECURITY RULES"
echo "   - Firestore → Rules"
echo "   - Update rules to allow authenticated access"
echo ""
echo "4️⃣  CREATE TEST USER"
echo "   - Authentication → Users"
echo "   - Add User: admin@artemadeira.com / admin123"
echo ""
echo "5️⃣  COMPILE NO ANDROID STUDIO"
echo "   - File → Sync with Gradle Files"
echo "   - Build → Clean Project"
echo "   - Build → Rebuild Project"
echo ""
echo "6️⃣  EXECUTAR APLICATIVO"
echo "   - Run → Run 'app' (Shift + F10)"
echo ""
echo "================================"
echo "Credenciais de Teste:"
echo "================================"
echo ""
echo "Email: admin@artemadeira.com"
echo "Senha: admin123"
echo ""
echo "================================"
